name: Deploy Backend

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Сборка JAR
        run: |
          javac -d out $(find . -name "*.java")
          jar cvfe backend.jar Main -C out .

      - name: Копирование на сервер
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend.jar"
          target: "/home/${{ secrets.SERVER_USER }}/app"

      - name: Перезапуск сервера
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/app
            pkill -f "java -jar backend.jar" || true
            nohup java -jar backend.jar > log.txt 2>&1 &
